### ISSUE TITLE
Color coding issue due to comments

### ISSUE THREAD

**Issue by gsscoder** [JustusAdam/language-haskell#104]
It's more easy to just see [this shot](https://imgur.com/a/nuRxx4S).

My system is **macOS**.

Thanks you for the extension!

**Comment by JustusAdam** [comment]
Ah yes. That is because export lists span multiple lines. So in order to match against it in the grammar we use a multi line matcher. The regex used to match the end is just a literal `where`.

To fix this we need to add a negative lookup for a comment begin before that. There are however two difficulties here

1. There can be arbitrarily many characters between the `--` and the `where` (such as the `)` in your example.
2. Its likely impossible to make this work in the case of multiline comments. I am not 100% sure but if you had something like
    ```hs
    module M (
      {-
        where -}
     ) where
    ```
    I am pretty sure that would be not parseable (within reasonable complexity) with the limitations of texmate parsers

I am not sure when I'll get around to addressing this, if anyone wants to take a stab at it, go for it.

**Comment by gsscoder** [comment]
It's nothing really affect your extension or how people can benefit from using it... I reported just to let you know.
Have a nice day

**Comment by JustusAdam** [comment]
I fixed this issue in so far that it should now be possible to use comments instead of export lists.
However it will still be weird if there is a `where` in the comment, and I don't see a way to fix it due to how restrictive the texmate grammars are.
