### ISSUE TITLE
Top level definition beginning with `pattern` is incorrectly highlighted

### ISSUE THREAD

**Issue by mbuszka** [JustusAdam/language-haskell#156]
Bug observed on version 3.0.0.

![bug-pattern](https://user-images.githubusercontent.com/10052477/81339189-0cb32e00-90ae-11ea-955e-67bf1d4f5712.png)

**Comment by sheaf** [comment]
Thanks for the bug report! That issue has since been fixed; there'll be a new release within the next few days.

I found out that some other keywords were causing the same issue (`via`, and `forall` in types), and those had not been fixed! So thanks for the report, it was useful.

Regression test in `T0156`.
