### ISSUE TITLE
syntax highlighting stops after using list comprehension

### ISSUE THREAD

**Issue by Da-Viper** [JustusAdam/language-haskell#176]
for example something like this to get the above average numbers 

```
aboveAverage :: (Ord a, Fractional a) => a -> a -> a -> Int
aboveAverage x y z  = length [a| a <- [x,y,z], a > average x y z ]
```

after a code like this syntax highlighting does not work anymore

**Comment by sheaf** [comment]
Hi, thanks for the bug report.

The problem is that [quasi-quotation syntax and list comprehension syntax ambiguously overlap](https://gitlab.haskell.org/ghc/ghc/-/issues/11679). This means you have to write list comprehension syntax using spaces:

```haskell
length [ a | a <- [x,y,z], a > average x y z ]
```

You'll notice the syntax highlighting that GitHub uses exhibits the same issue:

```haskell
length [a| a <- [x,y,z], a > average x y z ]

f :: x -> x
f a = x -- this isn't highlighted because the above list comprehension is interpreted as a quasi-quote which has not been terminated
```

**Comment by Da-Viper** [comment]
@sheaf  thanks it fixed it just  started learning haskell and i have not heard of the former
