### ISSUE TITLE
Not properly highlighted with signature comments

### ISSUE THREAD

**Issue by Meowcolm024** [JustusAdam/language-haskell#182]
<img width="309" alt="螢幕截圖 2021-02-21 下午8 28 02" src="https://user-images.githubusercontent.com/23007687/108624994-4d383880-7483-11eb-8d53-161f4f7997e9.png">

I'm using the `Ayu Dark Bordered` Theme (but I think it is not related to the theme)

**Comment by sheaf** [comment]
Thanks for the bug report. I am however unable to reproduce the bug on my end:

![t0182](https://user-images.githubusercontent.com/1297748/108625459-5dccbc80-744b-11eb-9117-dc082bccfc81.png)

The latest version hasn't been uploaded to the VS Code marketplace, so in the meantime I'm attaching the latest version of the syntax highlighting rules, so that you can check that they fix the issue:
[haskell.zip](https://github.com/JustusAdam/language-haskell/files/6017704/haskell.zip)
Just replace `syntaxes/haskell.json` with this file in the extension folder.

**Comment by Meowcolm024** [comment]
Oh thx, I would try. :)

**Comment by Meowcolm024** [comment]
The new file seems solved the issue :D
I'm closing the issue now.
Thanks a lot.
