### ISSUE TITLE
module' ("module" then a "prime" symbol) is incorrectly highlight as a keyword

### ISSUE THREAD

**Issue by SelectricSimian** [JustusAdam/language-haskell#31]
The identifier `module'` triggers the syntax highlighting associated with the normal `module` keyword, even though the inclusion of the prime/single-quote symbol should turn it into an ordinary, non-reserved identifier.  Importantly, all text after the identifier `module'` is highlighted as though it were part of a module declaration, which can seriously break syntax highlighting on large parts of valid source files.

Here's an example of the incorrect syntax highlighting for the identifier `module'`:

![screenshot from 2017-06-26 15-54-41](https://user-images.githubusercontent.com/3156539/27563736-4067a622-5a88-11e7-8d82-fe9a466f30d4.png)

And an example of correct syntax highlighting for the identifier `module_`:

![screenshot from 2017-06-26 15-56-28](https://user-images.githubusercontent.com/3156539/27563758-5d6430ce-5a88-11e7-890b-b6132feb76cd.png)

**Comment by JustusAdam** [comment]
The problem is this line `\b(module)\b` where it requires a word end after module. The problem is that the regex implementation does not recognise the `'` as a word character. 
I assume the same (or a similar one would be present if you tried using `import'` as an identifier or `let'`).
I assume something like `(\b(?!'))` might fix it.

**Comment by JustusAdam** [comment]
That regex fixed it. I also applied the same technique to all other keywords like `let'`, `import'` etc.
I'd appreciate if you can check that it I got them all.
