### ISSUE TITLE
Different colors for record names in `data` with record syntax

### ISSUE THREAD

**Issue by shlok** [JustusAdam/language-haskell#38]
Note the different colors:

<img width="330" alt="data" src="https://user-images.githubusercontent.com/3000933/27990245-ee95ef90-643f-11e7-984e-615b67c0f09d.png">

**Comment by JustusAdam** [comment]
Yes, I was aware of this already.

The reason for this bug is that the record fields and their type signatures actually have no special parsing.
They are handled like any other line of code.
It just so happens that fields which are not preceded by a comma (or curly brace) on the same line look like signature definitions of functions, thus the field label has the same color as a function and the other labels look like inline type signatures, hence no special highlighting for the field.

There are two ways to fix this. 

1. (quick and dirty) Don't highlight function names in signature definitions
2. Add special treatment for a data definition by writing proper parse rules for it.

As I'll want to do Nr 2 at some point anyways to properly distinguish types and constructors in data definitions at some point I think I'll go with that. 
Not sure yet when I'll get around to it though.
