### ISSUE TITLE
Incorrect highlighting of empty typeclass

### ISSUE THREAD

**Issue by FuzzyWuzzyBMP** [JustusAdam/language-haskell#66]
A class without any associated functions, e.g. just `class A a`, is valid Haskell, but gets highlighted incorrectly, as does everything following it.

Correct highlighting of non-empty class:
![correct](https://user-images.githubusercontent.com/13451773/47317064-e8693b00-d648-11e8-812d-21da66143829.png)

Incorrect highlighting of empty class:
![incorrect](https://user-images.githubusercontent.com/13451773/47317065-e901d180-d648-11e8-8c69-b45cfca218e9.png)

**Comment by cjenn** [comment]
I just encountered this issue, and it's pretty annoying, due to its ability to wipe out highlighting for an entire file.

The bug appears to affect everything up until the next `where`, after which it returns to normal.

![highlight-bug](https://user-images.githubusercontent.com/47906531/55522382-5418f080-564a-11e9-9ed8-a3dd759d4176.png)

Notably, this only happens for class declarations and not instance declarations.

**Comment by JustusAdam** [comment]
Hmm ... I guess for the time being you can just add the `where`. For empty type class (instances) it is optional

**Comment by JustusAdam** [comment]
Note to self: This issue may be fixable, by amending `endCaptures` to not only trigger on `where` but also a non-empty, unindented line
