### ISSUE TITLE
Proposal : Hightlight the function/variable name like the signature ?

### ISSUE THREAD

**Issue by wcastand** [JustusAdam/language-haskell#77]
Hi, first thank for the plugin ! :)

I was wondering if it would be possible to highlight the name of the function in the declaration like it's highlighted in the signature ? 
(In the screenshot, i'm talking about `one` or `two` `parsedOne` in case i described poorly :) )
The same color as the type signature would be nice but an other works for me too i guess :)

<img width="390" alt="screenshot 2018-12-07 at 03 54 05" src="https://user-images.githubusercontent.com/2178244/49624994-01993180-f9d4-11e8-915b-d01a7705a696.png">

**Comment by JustusAdam** [comment]
I haven't tested it but I think it is possible so long as the `=` sign follows on the same line.
However implementing this correctly is tricky. Particularly because one would also want to highlight class methods, which are indented which then begs the question how do we distinguish a method definition from say a `where` block?

Would you want `where` definitions to be highlighted too? What about `let` definitions? 

For top-level functions it is possible, but I don't think I'll have time soon to investigate how to also make it work for methods.

**Comment by wcastand** [comment]
Yeah, `where` and `let` seems tricky, i would probably only want that for the top-level.
But maybe it will make it harder to differentiate each one.

**Comment by JustusAdam** [comment]
So I think the main issue is that, as mentioned, it only works if the `=` is on the same line. 
A definition like this

```hs
class C SomeType where
  someFunction
      (SomeLongConstructor ...) 
      (Another long pattern match ...) =
```

Looks to the parser the same as:

```
... = do
  someFunction
  ...
```

Because the `someFuntion` line is the same for both. 

My feeling is that it would be too confusing to highlight the functions where the `=` is present and not the other ones, since they are fairly common. Plus this arises not only with long pattern matches, but also if you use guards with new lines.
