### ISSUE TITLE
No highlighting

### ISSUE THREAD

**Issue by janat08** [JustusAdam/language-haskell#80]
![screenshot_20190122_104424](https://user-images.githubusercontent.com/11337345/51513004-cdb68600-1e32-11e9-9610-3c09472271a2.png)
It would appear I have malfunction.

Operating System: KDE neon 5.14
KDE Plasma Version: 5.14.5
Qt Version: 5.11.2
KDE Frameworks Version: 5.54.0
Kernel Version: 4.15.0-43-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-5930K CPU @ 3.50GHz
Memory: 15.5 GiB of RAM

**Comment by janat08** [comment]
I tried installing hie via nix which the server didn't recognize, and then tried stack.

**Comment by JustusAdam** [comment]
What exactly are you expecting? This looks perfectly fine to me. If the highlighting wasn't working all the text you see would be white.

Perhaps your problem is that you are using the default theme `Light` or `Light+` which only colors very few kinds of syntax elements. If that is the case you should try selecting a different theme like `Monokai` or `Dark+` which colors more syntax elements.

**Comment by JustusAdam** [comment]
FYI for the highlighting to work you do not need `hie` or any other program.

**Comment by janat08** [comment]
The hie is working, and I have dark+.

**Comment by JustusAdam** [comment]
Again, as I told you before, use a different Theme. The demo screenshots were taken using the `Monokai` theme. Simply open the command pallet, select `Color Themes` and switch to `Monokai` that should give you the same as the screenshot
